dns_dir: "{{ docker_compose_dir }}/dns"
dns_config_dir: "{{ dns_dir }}/config"
dns_cache_dir: "{{ dns_dir }}/cache"

dns_forwarders:
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844
  - 8.8.8.8
  - 8.8.4.4
  - "{{ isp_dns_forwarder_1 }}"
  - "{{ isp_dns_forwarder_2 }}"

dns_server: ns01
dns_zone: infrastructure
dns_hostname: "{{ dns_server }}.{{ dns_zone }}.{{ network.domain }}.{{ network.suffix }}"