media_server_role:
  directories:
    - path: "{{ media_server_dir }}"
      volume:
        name: plex_config
  nas_directories:
    - path: "{{ secrets['nas_media_dir'] }}"
      volume:
        name: media
  docker:
    service:
      name: plex
      image: linuxserver/plex
      environment:
        - VERSION=docker
      volumes:
        - plex_config:/config
        - media:/media
      ports:
        - 32400:32400
        - 32400:32400/udp
        - 32469:32469
        - 32469:32469/udp
        - 1900:1900/udp
        - 3005:3005
        - 8324:8324
        - 32410:32410/udp
        - 32411:32411/udp
        - 32412:32412/udp
        - 32413:32413/udp
        - 32414:32414/udp
