private_reverse_proxy_dir: "{{ docker_compose_dir }}/nginx-private"
public_reverse_proxy_dir: "{{ docker_compose_dir }}/nginx-public"

reverse_proxy_private0_ipv4_address: "{{ secrets['reverse_proxy_private0_ipv4_address'] }}"

reverse_proxy_public_domain: "{{ secrets.reverse_proxy_public_domain }}"

reverse_proxy_config_volume: public-nginx-config
reverse_proxy_log_volume: public-nginx-log
reverse_proxy_service_name: public-nginx
reverse_proxy_public_network: public0
