reverse_proxy_dir: "{{ docker_compose_dir }}/reverse-proxy"

reverse_proxy_config_volume: proxy-config
reverse_proxy_bridge_network: proxy-bridge
reverse_proxy_external_network: proxy-external

reverse_proxy_internal_log_volume: internal-proxy-log
reverse_proxy_internal_site_configs_volume: internal-proxy-site-configs
reverse_proxy_internal_service_name: internal-proxy

reverse_proxy_external_log_volume: external-proxy-log
reverse_proxy_external_site_configs_volume: external-proxy-site-configs
reverse_proxy_external_service_name: external-proxy