- name: Load reverse proxy networks
  set_fact:
    reverse_proxy_internal_networks: "{{ reverse_proxy_networks }}"

- name: Install public site configs
  vars:
    domain: "{{ reverse_proxy_public_domain }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ public_reverse_proxy_dir }}/nginx/site-confs/{{ item.name }}"
  with_items: "{{ reverse_proxy_public_site_configs }}"
  register: reverse_proxy_public_site_config_installation
