- name: Load reverse proxy certificates
  set_fact:
    __reverse_proxy_certificate_volume: "{{ reverse_proxy_certificate_volume }}"

- name: Load reverse proxy configuration
  set_fact:
    __reverse_proxy_internal_networks: "{{ reverse_proxy_networks }}"
    __reverse_proxy_public_site_configs: "{{ reverse_proxy_public_site_configs }}"
