home_automation_dir: "{{ docker_compose_dir }}/home-automation"
hass_dir: "{{ home_automation_dir }}/hass"
hass_db_dir: "{{ home_automation_dir }}/hass-db"

google_assistant_project_id: "{{ secrets['google_assistant_project_id'] }}"
google_assistant_api_key: "{{ secrets['google_assistant_api_key'] }}"

home_automation_internal_web_port: 8123
home_automation_external_port: "{{ secrets['home_automation_external_port'] | default(home_automation_internal_web_port) }}"

hass_config_volume: hass-config
hass_db_volume: hass-db

home_automation_service_name: homeassistant
home_automation_container_name: hass
home_automation_subdomain: home

zwave_dir: "{{ home_automation_dir }}/zwave"

zwave_vendor: "{{ secrets['zwave_vendor'] }}"
zwave_product: "{{ secrets['zwave_product'] }}"
zwave_session_secret: "{{ secrets['zwave_session_secret'] }}"
zwave_s0_legacy_key: "{{ secrets['zwave_s0_legacy_key'] }}"
zwave_s2_unauthenticated_key: "{{ secrets['zwave_s2_unauthenticated_key'] }}"
zwave_s2_authenticated_key: "{{ secrets['zwave_s2_authenticated_key'] }}"
zwave_s2_access_control_key: "{{ secrets['zwave_s2_access_control_key'] }}"

zwave_usbstick_symlink: zwaveusbstick

zwave_config_volume: zwave-config
zwave_service_name: zwavejs2mqtt
zwave_http_port: 8091
zwave_websocket_port: 3000