hass_dir: "{{ docker_compose_dir }}/hass"
hass_db_dir: "{{ docker_compose_dir }}/hass-db"

google_assistant_project_id: "{{ secrets['google_assistant_project_id'] }}"
google_assistant_api_key: "{{ secrets['google_assistant_api_key'] }}"

hass_google_assistant_api: "{{ secrets['hass_google_assistant_api'] }}"
hass_auth_authorize: "{{ secrets['hass_auth_authorize'] }}"
hass_auth_token: "{{ secrets['hass_auth_token'] }}"

home_automation_wemo_server_port: 8990

hass_config_volume: hass-config
hass_db_volume: hass-db

home_automation_service_name: homeassistant
home_automation_container_name: hass

home_automation_network: ha-proxy0

home_automation_subnet: "{{ secrets['docker_private0_subnet'] | default('172.32.128.0/24') }}"
home_automation_reverse_proxy_ip: "{{ secrets['reverse_proxy_private0_ipv4_address'] | default('172.32.128.20') }}"