unifi_role:
  directories:
    - path: "{{ unifi_dir }}"
      volume:
        name: unifi
    - path: "{{ unifi_dir }}/data/backup"
      volume:
        name: unifi-backup
        backup: true
  docker:
    service:
      name: unifi
      image: linuxserver/unifi-controller
      volumes:
        - unifi:/config
      ports:
        - 3478:3478/udp
        - 10001:10001/udp
        - 8080:8080
        - 8081:8081
        - 8443:8443
        - 8843:8843
        - 8880:8880
        - 6789:6789
      backup: true
