unifi_role:
  directories:
    - path: "{{ unifi_dir }}"
      volume:
        name: "{{ unifi_volume }}"
    - path: "{{ unifi_dir }}/data/backup"
      volume:
        name: "{{ unifi_backups_volume }}"
        backup: true
    - path: "{{ unifi_dir }}/mongodb/db"
      volume:
        name: "{{ unifi_mongodb_volume }}"
    - path: "{{ unifi_dir }}/mongodb/init"
  files:
    - src: roles/unifi/templates/Dockerfile
      dest: "{{ dockerfile_dir }}/{{ unifi_service_name }}.Dockerfile"
    - src: roles/unifi/templates/mongodb.Dockerfile
      dest: "{{ dockerfile_dir }}/{{ unifi_mongodb_service_name }}.Dockerfile"
    - src: roles/unifi/templates/init-mongo.js.j2
      dest: "{{ unifi_dir }}/mongodb/init/init-mongo.js"
  docker:
    services:
      - name: "{{ unifi_service_name }}"
        volumes:
          - "{{ unifi_volume }}:/config"
        ports:
          - 3478:3478/udp
          - 10001:10001/udp
          - 8080:8080
          - 8081:8081
          - "{{ unifi_ui_port }}:8443"
          - 8843:8843
          - 8880:8880
          - 6789:6789
        backup: true
      - name: "{{ unifi_mongodb_service_name }}"
        volumes:
          - "{{ unifi_mongodb_volume }}:/data/db"
          - "{{ unifi_dir }}/mongodb/init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"