media_rip_role:
  udev_devices:
    - subsystem: block
      attrs:
        vendor: "{{ optical_vendor }}"
      symlink: "{{ media_rip_block_device_symlink }}"
    - subsystem: scsi_generic
      attrs:
        vendor: "{{ optical_vendor }}"
      symlink: "{{ media_rip_scsi_generic_device_symlink }}"
  directories:
    - path: "{{ media_rip_config_dir }}"
      volume:
        name: media_rip_config
    - path: "{{ media_rip_output_dir }}"
      volume:
        name: "{{ media_rip_output_volume }}"
  docker:
    service:
      name: makemkv
      image: jlesage/makemkv
      ports:
        - 5801:5800
      environment:
        - USER_ID=1000
        - GROUP_ID=999
        - KEEP_APP_RUNNING={{ media_rip_keep_app_running }}
        - AUTO_DISC_RIPPER=1
      volumes:
        - "{{ media_rip_output_volume }}:/output"
        - media_rip_config:/config
      devices:
        - "{{ ('/dev/' + media_rip_block_device_symlink) | realpath }}:{{ ('/dev/' + media_rip_block_device_symlink) | realpath }}"
        - "{{ ('/dev/' + media_rip_scsi_generic_device_symlink) | realpath }}:{{ ('/dev/' + media_rip_scsi_generic_device_symlink) | realpath }}"
  provides:
    output_volume: "{{ media_rip_output_volume }}"
