version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker"
    directory: "/roles/backup/templates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker"
    directory: "/roles/certificates/templates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker"
    directory: "/roles/ddns/templates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker"
    directory: "/roles/dhcp-relay/templates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker"
    directory: "/roles/dhcp/templates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker"
    directory: "/roles/dns/templates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker"
    directory: "/roles/home-automation/templates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
    groups:
      docker:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/roles/media-rip/templates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker"
    directory: "/roles/media-server/templates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker"
    directory: "/roles/reverse-proxy/templates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker"
    directory: "/roles/transcode/templates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker"
    directory: "/roles/unifi/templates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker"
    directory: "/roles/zwave/templates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"