version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "pip"
    directory: "/roles/certbot/files"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker-compose"
    directory: "/roles/plex/vars"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"
  - package-ecosystem: "docker-compose"
    directory: "/roles/handbrake/vars"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "America/Toronto"