version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "America/Toronto"
  - package-ecosystem: "pip"
    directory: "/roles/certbot/files"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "America/Toronto"
