- name: Find reverse proxy subdomains
  gather_facts: false
  hosts: reverse_proxies
  tasks:
    - set_fact:
        reverse_proxies_subdomains: "{{ reverse_proxies_lazy_subdomains }}"

- name: Setup hypervisors
  hosts: hypervisors
  roles:
    - proxmox
    - yubikey

- name: Setup DHCP Container
  hosts: dhcp
  gather_facts: false
  roles:
    - container

- name: Setup DHCP Server
  hosts: dhcp
  roles:
    - kea

- name: Setup Containers
  hosts: regular_priority_lxcs
  gather_facts: false
  roles:
    - container

- name: Setup VMs
  hosts: vms
  gather_facts: false
  roles:
    - virtual_machine

- name: Setup DNS Server
  hosts: dns
  roles:
    - bind9

- name: Setup Proxy Cache
  hosts: proxy-cache
  roles:
    - nginx

- name: Setup Linux Systems
  hosts: linuxes
  roles:
    - core

- name: Setup SSH Servers
  hosts: ssh_servers
  roles:
    - ssh_server

- name: Setup Docker Hosts
  hosts: docker_hosts
  roles:
    - docker_host

- name: Setup Media Server
  hosts: media
  roles:
    - handbrake
    - plex

- name: Setup Network Management
  hosts: network-management
  roles:
    - unifi

- name: Setup Reverse Proxy
  hosts: reverse-proxy
  roles:
    - certbot
    - nginx

- name: Setup HTTP Firewall
  hosts: http-firewall
  roles:
    - nginx

- name: Setup cloudflare tunnel
  hosts: tunnel
  roles:
    - cloudflared

- name: Cleanup Docker Hosts
  hosts: docker_hosts
  tasks:
    - include_role:
        name: docker_host
        tasks_from: prune.yml

- name: Cleanup Linux Systems
  hosts: linuxes
  tasks:
    - include_role:
        name: core
        tasks_from: prune.yml

- name: Copy secrets
  gather_facts: false
  hosts:
    - nas
  tasks:
    - synchronize:
        src: "{{ item }}"
        dest: "{{ ansible_ssh_host}}:{{ nas_backup_vault_path }}"
        delete: true
      loop:
        - host_vars
        - group_vars
