- hosts: all
  become: true
  pre_tasks:
    - name: Add apt keys
      apt_key:
        url: "{{ item.url }}"
      with_items: "{{ apt_keys }}"

    - name: Add PPAs
      apt_repository:
        repo: "ppa:{{ item.ppa }}"
        codename: "{{ item.codename | default(ansible_distribution_release) }}"
      with_items: "{{ apt_ppas }}"

    - name: Add deb repos
      apt_repository:
        repo: "deb [arch=amd64] {{ item.url }} {{ item.codename | default(ansible_distribution_release) }} {{ item.channel | default('stable') }}"
      with_items: "{{ deb_repos }}"

    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true

    - name: Upgrade packages
      apt:
        upgrade: "yes"

    - name: Install jmespath
      local_action:
        module: pip
        name: jmespath

    - name: Include role secrets
      include_vars: "{{ path }}"
      vars:
        params:
          files: "{{ secrets_files }}"
          paths: "{{ 'roles/' + item + '/vars' }}"
          skip: true
        path: "{{ lookup('first_found', params) }}"
      when: path | length > 0
      loop: "{{ ansible_role_names }}"

  roles:
    - security
    - docker
    - shell
    - system-config

  post_tasks:
    - name: Start services on boot
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items: "{{ services }}"

    - name: Remove unused packages
      apt:
        autoremove: yes

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes
