- name: Create .ssh directory
  file:
    path: /home/{{ ansible_env.SUDO_USER }}/.ssh
    state: directory

- name: Update authorized_keys
  template:
    src: authorized_keys.j2
    dest: /home/{{ ansible_env.SUDO_USER }}/.ssh/authorized_keys
    mode: 0600