- name: Create key directories
  file:
    path: /home/{{ ansible_env.SUDO_USER }}/{{ item }}
    state: directory
  with_items:
    - .ssh
    - .yubico

- name: Update authorized_keys
  template:
    src: authorized_keys.j2
    dest: /home/{{ ansible_env.SUDO_USER }}/.ssh/authorized_keys
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0600

- name: Update authorized_yubikeys
  template:
    src: authorized_yubikeys.j2
    dest: /home/{{ ansible_env.SUDO_USER }}/.yubico/authorized_yubikeys
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0600