- name: Update authorized_keys
  template:
    src: authorized_keys.j2
    dest: /home/{{ ansible_env.SUDO_USER }}/.ssh/authorized_keys
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0600

- name: Update authorized_yubikeys
  template:
    src: authorized_yubikeys.j2
    dest: /home/{{ ansible_env.SUDO_USER }}/.yubico/authorized_yubikeys
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0600

- name: Create system config directories
  file:
    path: /etc/{{ item }}
    state: directory
  with_items:
    - pam.d
    - ssh

- name: Update pam.d files
  template:
    src: pam.{{ item }}.j2
    dest: /etc/pam.d/{{ item }}
  with_items:
    - sshd
    - login

- name: Update gpg-agent.conf
  copy:
    src: gpg-agent.conf
    dest:  /home/{{ ansible_env.SUDO_USER }}/.gnupg/gpg-agent.conf 

- name: Update sshd config
  copy:
    src: sshd_config
    dest: /etc/sshd_config
  notify: Restart SSHD
