- include_tasks:
    file: "{{ ansible_distribution_file_variety | lower }}.yml"

- become: true
  block:
    - name: Disable unused services
      service:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop:
        - kea-dhcp6-server
        - kea-dhcp-ddns-server
        - kea-ctrl-agent

    - name: Install kea configuration
      template:
        src: kea-dhcp4.conf.j2
        dest: /etc/kea/kea-dhcp4.conf
      notify: Reload kea
