- name: Add iptable rules
  iptables:
    action: insert
    chain: "{{ item.chain }}"
    in_interface: "{{ item.in_interface }}"
    ctstate: "{{ item.cstate }}"
    jump: "{{ item.jump }}"
  loop: "{{ iptables_rules }}"
  notify: restart netfilter-persistent
