- become: true
  block:
    - name: Install common packages
      apt:
        name:
          - gpg
          - htop
          - nfs-common
          - python3-debian
          - vim
          - virtualenv
        update_cache: true

    - name: Upgrade packages
      apt:
        upgrade: dist
        cache_valid_time: "{{ core_apt_cache_valid_time }}"