services:
  plex:
    container_name: plex
    image: linuxserver/plex:1.41.3
    environment:
      - TZ={{ plex_timezone }}
      - PUID={{ plex_uid }}
      - PGID={{ plex_gid }}
      - VERSION=docker
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 1900:1900/udp
      - 3005:3005
      - 8324:8324
      - 32410:32410/udp
      - 32411:32411/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: always
    volumes:
      - config:/config
      - media:/media
volumes:
  config:
    driver: local
    driver_opts:
      device: /opt/epcot/plex/config
      o: bind
      type: none
  media:
    driver: local
    driver_opts:
      device: :{{ plex_nfs_mountpoint }}
      o: addr={{ plex_nfs_address }},rw,nfsvers=4,async
      type: nfs
