ddns_role:
  docker:
    service:
      name: "{{ duckdns_service_name}}"
      image: linuxserver/duckdns
      environment:
        - SUBDOMAINS={{ duckdns_subdomain }}
        - TOKEN={{ duckdns_token }}
  provides:
    duckdns_token: "{{ duckdns_token }}"
  files:
    - src: roles/ddns/templates/Dockerfile
      dest: "{{ dockerfile_dir }}/{{ duckdns_service_name }}.Dockerfile"
