volumerize_passphrase: "{{ lookup('lastpass', lastpass_secrets_path + '/volumerize_passphrase') }}"
volumerize_email: "{{ lookup('lastpass', lastpass_secrets_path + '/volumerize_email') }}"
volumerize_google_drive_dir: "{{ lookup('lastpass', lastpass_secrets_path + '/volumerize_google_drive_dir') }}"
