- name: Restart docker daemon
  service:
    name: docker
    state: restarted
  loop: "{{ all_changed_files | selectattr('dest', 'match', docker_compose_dir + '/docker-compose.yml') | selectattr('changed', 'equalto', true) | map(attribute='item') }}"

- name: Stop docker containers
  vars:
    ansible_python_interpreter: "{{ docker_compose_virtual_env }}/bin/python3"
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    state: stopped
  loop: "{{ all_changed_files | selectattr('dest', 'match', docker_compose_dir + '/docker-compose.yml') | selectattr('changed', 'equalto', true) | map(attribute='item') }}"
