role_var_names: "{{ lookup('varnames', '^(?!local_).+_role$').split(',') }}"
role_vars: "{%- set temp_role_vars = [] -%}
            {%- for role_var in role_var_names -%}
            {%- set _ = temp_role_vars.append(lookup('vars', role_var)) -%}
            {%- endfor -%}
            {{- temp_role_vars -}}"

apt_ppas: "{{ role_vars | selectattr('apt_ppa', 'defined') | map(attribute='apt_ppa') | list }}"
deb_repos: "{{ role_vars | selectattr('deb_repo', 'defined') | map(attribute='deb_repo') | list }}"
apt_keys: "{{ role_vars | selectattr('apt_key', 'defined') | map(attribute='apt_key') | list }}"
packages: "{{ role_vars | selectattr('packages', 'defined') | sum(attribute='packages', start=[]) | list }}"
services: "{{ role_vars | selectattr('service', 'defined') | map(attribute='service') | list }}"
all_udev_devices: "{{ role_vars | selectattr('udev_devices', 'defined') | map(attribute='udev_devices') | flatten }}"
directories: "{{ (role_vars | selectattr('directories', 'defined') | map(attribute='directories') | flatten) + [{ 'path': dockerfile_dir}] }}"
nas_directories: "{{ role_vars | selectattr('nas_directories', 'defined') | map(attribute='nas_directories') | flatten }}"
files: "{{ role_vars | selectattr('files', 'defined') | map(attribute='files') | flatten }}"
iptable_rules: "{{ role_vars | selectattr('iptable_rules', 'defined') | map(attribute='iptable_rules') | flatten }}"
disabled_services: "{{ role_vars | selectattr('disabled_services', 'defined') | map(attribute='disabled_services') | flatten | unique }}"

pip_modules: "{{ role_vars | selectattr('pip_modules', 'defined') | map(attribute='pip_modules') | flatten }}"
virtual_environments: "{{ pip_modules | selectattr('environment', 'defined') | map(attribute='environment') | unique }}"

usernames: "{{ users | map(attribute='name') | list }}"
all_users: "{{ usernames + (role_vars | selectattr('users', 'defined') | map(attribute='users') | flatten) }}"

user_groups: "{{ role_vars | selectattr('groups', 'defined') | map(attribute='groups') | flatten }}"
user_group_names: "{{ user_groups | map(attribute='name') | unique }}"
user_group_users: "{{ user_groups | subelements('users') }}"
group_names_to_zip: "{{ user_group_users | map('first') | map(attribute='name') }}"
user_names_to_zip: "{{ user_group_users | map('last') }}"
unique_user_group_mappings: "{{ group_names_to_zip | zip(user_names_to_zip) | unique }}"

intrusion_detection: "{{ role_vars | selectattr('intrusion_detection', 'defined') | map(attribute='intrusion_detection') }}"
intrusion_jails: "{{ intrusion_detection | selectattr('jails', 'defined') | map(attribute='jails') | flatten }}"
intrusion_filters: "{{ intrusion_detection | selectattr('filters', 'defined') | map(attribute='filters') | flatten }}"

all_reverse_proxy_configs: "{{ role_vars | selectattr('reverse_proxy', 'defined') | map(attribute='reverse_proxy') }}"
all_reverse_proxy_networks: "{{ all_reverse_proxy_configs | selectattr('networks', 'defined') | map(attribute='networks') | flatten }}"

docker_config: "{{ role_vars | selectattr('docker', 'defined') | map(attribute='docker') | flatten }}"
all_docker_services: "{{ docker_config | selectattr('services', 'defined') | map(attribute='services') | flatten }}"
all_docker_services_with_config: "{{ docker_services | selectattr('config_dir', 'defined') | map(attribute='name') }}"

local_docker_volumes: "{{ directories | selectattr('volume', 'defined') }}"
nas_docker_volumes: "{{ nas_directories | selectattr('volume', 'defined') }}"

backed_up_services: "{{ all_docker_services | selectattr('backup', 'defined') | selectattr('backup', 'equalto', true) }}"
backed_up_volumes: "{{ local_docker_volumes | map(attribute='volume') | selectattr('backup', 'defined') | selectattr('backup', 'equalto', true) | map(attribute='name') }}"

extra_docker_networks: "{{ docker_config | selectattr('networks', 'defined') | map(attribute='networks') | flatten }}"

all_changed_files: "{{ changed_files.results }}"

lastpass_secrets_path: Infrastructure/Secrets

secrets_files:
  - lastpass.yml

docker_compose_dir: "{{ secrets['docker_compose_dir'] | default('/opt/docker-services') }}"
dockerfile_dir: "{{ docker_compose_dir }}/dockerfiles"

network_hosts: "{%- set temp_network_hosts = {} -%}
                {%- for zone in network.zones -%}
                {%- for host in zone.hosts -%}
                {%- set host_name = [host.name, zone.name] | join('.') -%}
                {%- set host_with_zone = host -%}
                {%- set _ = host_with_zone.update({ 'zone': zone.name }) -%}
                {%- set _ = temp_network_hosts.update({ host_name: host_with_zone }) -%}
                {%- endfor -%}
                {%- endfor -%}
                {{- temp_network_hosts -}}"

wemo_hosts: "{{ network_hosts | dict2items | json_query('[?value.wemo]') | map(attribute='value') }}"

nas_host: "{{ network_hosts | dict2items | json_query('[?value.nas]') | map(attribute='value') | first }}"
nas_zone: "{{ network.zones | selectattr('name', 'equalto', nas_host.zone) | first }}"
nas_ip: "{{ nas_zone.ipv4_subnet | ansible.utils.ipaddr(nas_host.ipv4_offset) | ansible.utils.ipaddr('address') }}"

media_mountpoint: "{{ (network_hosts | dict2items | json_query('[?value.nas.mountpoints.media]') | first).value.nas.mountpoints.media }}"

reverse_proxy_docker_ip_address: "{{ secrets['reverse_proxy_docker_ip_address'] | default('172.32.2.2') }}"

