role_var_names: "{{ lookup('varnames', '_role$').split(',') }}"
role_vars: "{%- set temp_role_vars = [] -%}
            {%- for role_var in role_var_names -%}
            {%- set _ = temp_role_vars.append(lookup('vars', role_var)) -%}
            {%- endfor -%}
            {{- temp_role_vars -}}"

apt_ppas: "{{ role_vars | selectattr('apt_ppa', 'defined') | map(attribute='apt_ppa') | list }}"
deb_repos: "{{ role_vars | selectattr('deb_repo', 'defined') | map(attribute='deb_repo') | list }}"
apt_keys: "{{ role_vars | selectattr('apt_key', 'defined') | map(attribute='apt_key') | list }}"
packages: "{{ role_vars | selectattr('packages', 'defined') | sum(attribute='packages', start=[]) | list }}"
services: "{{ role_vars | selectattr('service', 'defined') | map(attribute='service') | list }}"
udev_devices: "{{ role_vars | selectattr('udev_devices', 'defined') | map(attribute='udev_devices') | flatten }}"

lastpass_secrets_path: Infrastructure/Secrets

secrets_files:
  - lastpass.yml

resolve_search: "{{ network.domain }}.{{ network.suffix }}"

docker_compose_dir: "{{ secrets['docker_compose_dir'] }}"
