user_security_directories: "{%- set temp_user_security_directories = [] -%}
                            {%- for user in (__security_users | default([])) -%}
                            {%- set home = __security_user_details | selectattr('name', 'equalto', user) | map(attribute='home') | first -%}
                            {%- set group = __security_user_details | selectattr('name', 'equalto', user) | map(attribute='group') | first -%}
                            {%- set _ = temp_user_security_directories.append({'path': home + '/.gnupg', 'owner': user, 'group': group, 'mode': '0700' })-%}
                            {%- set _ = temp_user_security_directories.append({'path': home + '/.ssh', 'owner': user, 'group': group, 'mode': '0700' })-%}
                            {%- set _ = temp_user_security_directories.append({'path': home + '/.config/Yubico', 'owner': user, 'group': group })-%}            
                            {%- endfor -%}
                            {{- temp_user_security_directories }}"

user_security_files: "{%- set temp_user_security_files = [] -%}
                      {%- for user in (__security_users | default([])) -%}
                      {%- set home = __security_user_details | selectattr('name', 'equalto', user) | map(attribute='home') | first -%}
                      {%- set group = __security_user_details | selectattr('name', 'equalto', user) | map(attribute='group') | first -%}
                      {%- set _ = temp_user_security_files.append({
                          'src': 'roles/security/files/gpg-agent.conf',
                          'dest': home + '/.gnupg/gpg-agent.conf',
                          'owner': user,
                          'group': group
                      })-%}
                      {%- set _ = temp_user_security_files.append({
                          'src': 'roles/security/templates/authorized_keys.j2',
                          'dest': home + '/.ssh/authorized_keys',
                          'owner': user,
                          'group': group,
                          'mode': '0600',
                          'vars': { 'ssh_authorized_key': secrets[user + '_ssh_authorized_key'] },
                          'label' : user + \"'s ssh public key\"
                      })-%}                          
                      {%- endfor -%}
                      {{- temp_user_security_files }}"

core_security_directories:
  - path: /etc/pam.d
  - path: /etc/ssh

core_security_files:
  - src: roles/security/templates/pam.login.j2
    dest: /etc/pam.d/login
  - src: roles/security/files/sshd_config
    dest: /etc/ssh/sshd_config
    notify: Restart sshd

security_directories: "{{ user_security_directories + core_security_directories }}"
security_files: "{{ user_security_files + core_security_files }}"

security_role:
  apt_ppa:
    ppa: yubico/stable
  packages:
    - libpam-u2f
    - openssh-server
    - scdaemon
  service: sshd
  directories: "{{ security_directories }}"
  files: "{{ security_files }}"
