security_role:
  apt_ppa:
    ppa: yubico/stable
  packages:
    - libpam-yubico
    - openssh-server
    - scdaemon
    - yubikey-manager
  service: sshd
  directories:
    - path: /home/{{ ansible_env.SUDO_USER }}/.gnupg
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
    - path: /home/{{ ansible_env.SUDO_USER }}/.ssh
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
    - path: /home/{{ ansible_env.SUDO_USER }}/.yubico
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
    - path: /etc/pam.d
    - path: /etc/ssh
  files:
    - src: roles/security/templates/authorized_keys.j2
      dest: /home/{{ ansible_env.SUDO_USER }}/.ssh/authorized_keys
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
      mode: "0600"
    - src: roles/security/templates/authorized_yubikeys.j2
      dest: /home/{{ ansible_env.SUDO_USER }}/.yubico/authorized_yubikeys
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
      mode: "0600"
    - src: roles/security/templates/pam.sshd.j2
      dest: /etc/pam.d/sshd
    - src: roles/security/templates/pam.login.j2
      dest: /etc/pam.d/login
    - src: roles/security/files/gpg-agent.conf
      dest: /home/{{ ansible_env.SUDO_USER }}/.gnupg/gpg-agent.conf
    - src: roles/security/files/sshd_config
      dest: /etc/sshd_config
      notify: Restart sshd
