security_role:
  apt_ppa:
    ppa: yubico/stable
  packages:
    - libpam-u2f
    - openssh-server
    - scdaemon
  service: sshd
  directories:
    - path: "{{ ansible_env.HOME }}/.gnupg"
    - path: "{{ ansible_env.HOME }}/.ssh"
    - path: "{{ ansible_env.HOME }}/.config/Yubico"
  root_directories:
    - path: /etc/pam.d
    - path: /etc/ssh
  files:
    - src: roles/security/templates/authorized_keys.j2
      dest: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
      mode: "0600"
    - src: roles/security/files/gpg-agent.conf
      dest: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"
  root_files:
    - src: roles/security/templates/pam.login.j2
      dest: /etc/pam.d/login
    - src: roles/security/files/sshd_config
      dest: /etc/ssh/sshd_config
      notify: Restart sshd
