- name: Update DNS records
  vars:
    line: "{{ item.split('|') }}"
    zone: "{{ line.0 }}"
    record: "{{ line.1 }}"
    type: "{{ line.2 }}"
    address: "{{ line.3 }}"
  nsupdate:
    key_name: "{{ network.domain }}.{{ network.suffix }}"
    key_secret: "{{ ddns_public_key.stdout }}"
    record: "{{ record }}"
    server: "{{ dns_hostname }}"
    type: "{{ type }}"
    value: "{{ address }}"
    zone: "{{ zone }}"
  with_lines:
    - cat {{ dns_config_dir }}/records.txt
