- name: Update DNS zone serial numbers
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  vars:
    serial_number_increment: 1
  loop: "{{ all_changed_files | selectattr('dest', 'match', '/tmp/db') | selectattr('changed', 'equalto', true) | map(attribute='item') }}"
  loop_control:
    label: "{{ item.zone_name }}"
