- name: Update DNS zone serial numbers
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  vars:
    serial_number_increment: 1
  loop: "{{ all_changed_files | selectattr('dest', 'match', dns_config_dir + '/db') | selectattr('changed', 'equalto', true) | map(attribute='item') }}"
  loop_control:
    label: "{{ item.zone_name }}"
