docker_role:
  deb_repo:
    url: "https://download.docker.com/linux/ubuntu"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - software-properties-common
    - docker-ce
    - docker-compose-plugin
  service: docker
  pip_modules:
    environment: "{{ docker_compose_virtual_env }}"
    modules:
    - docker
    - docker-composer-v2
  users:
    - "{{ docker_user_name }}"
  groups:
    - name: "{{ docker_group_name }}"
      users:
        - "{{ ansible_env.USER }}"
        - "{{ docker_user_name }}"
  root_files:
    - src: roles/docker/templates/daemon.json.j2
      dest: /etc/docker/daemon.json
      notify:
        - Restart docker daemon
        - Stop docker containers
  provides:
    docker_user: "{{ docker_user_name }}"
    docker_group: "{{ docker_group_name }}"
