docker_role:
  deb_repo:
    url: "https://download.docker.com/linux/ubuntu"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - software-properties-common
    - docker-ce
  service: docker
  pip_modules:
    environment: "{{ docker_virtual_env }}"
    modules:
    - docker
    - docker-compose
  groups:
    - name: "{{ docker_group_name }}"
      users:
        - "{{ ansible_env.USER }}"
  root_files:
    - src: roles/docker/templates/daemon.json.j2
      dest: /etc/docker/daemon.json
      notify:
        - Restart docker daemon
        - Stop docker containers
  files:
    - src: roles/docker/templates/docker-compose.yml.j2
      dest: "{{ docker_compose_dir }}/docker-compose.yml"

docker_builtin_networks:
  - name: "{{ docker_primary_network }}"

docker_default_environment:
  - TZ={{ TZ }}
  - PUID=1000
  - PGID=999

docker_local_volumes: "{{ local_docker_volumes }}"
docker_nas_volumes: "{{ nas_docker_volumes }}"
docker_nas_ip: "{{ nas_ip }}"
docker_extra_networks: "{{ extra_docker_networks }}"
docker_services: "{{ all_docker_services }}"
docker_services_with_config: "{{ all_docker_services_with_config }}"