docker_role:
  files:
    - src: roles/docker/templates/docker-compose.yml.j2
      dest: "{{ docker_compose_dir }}/docker-compose.yml"

docker_builtin_networks:
  - name: "{{ docker_primary_network }}"

docker_default_environment:
  - TZ={{ TZ }}
  - PUID=1000
  - PGID=999
