transcode_role:
  directories:
    - path: "{{ transcode_dir }}"
      volume:
        name: "{{ transcode_config_volume }}"
  files:
    - src: roles/transcode/templates/Dockerfile
      dest: "{{ dockerfile_dir }}/{{ transcode_service_name }}.Dockerfile"
  nas_directories:
    - path: "{{ transcode_nas_dir }}"
      volume:
        name: "{{ transcode_destination_volume }}"
  docker:
    services:
      - name: "{{ transcode_service_name }}"
        ports:
          - "{{ transcode_port }}:5800"
        environment:
          - USER_ID={{ __transcode_uid | default(0) }}
          - GROUP_ID={{ __transcode_gid | default(0) }}
          - KEEP_APP_RUNNING={{ transcode_keep_app_running }}
          - AUTOMATED_CONVERSION_PRESET={{ transcode_preset }}
          - AUTOMATED_CONVERSION_KEEP_SOURCE={{ transcode_keep_source_file }}
          - AUTOMATED_CONVERSION_OUTPUT_SUBDIR={{ transcode_output_subdir }}
          - AUTOMATED_CONVERSION_SOURCE_STABLE_TIME={{ transcode_input_stability_seconds }}
          - AUTOMATED_CONVERSION_CHECK_INTERVAL={{ transcode_input_check_seconds }}
        volumes:
          - "{{ transcode_config_volume }}:/config"
          - "{{ __transcode_src_volume | default('undefined') }}:/watch"
          - "{{ transcode_destination_volume }}:/output"
