zwave_rip_role:
  udev_devices:
    - subsystem: tty
      attrs:
        idVendor: "{{ zwave_vendor }}"
        idProduct: "{{ zwave_product }}"
      symlink: "{{ zwave_usbstick_symlink }}"
  directories:
    - path: "{{ zwave_dir }}"
