zwave_rip_role:
  udev_devices:
    - subsystem: tty
      attrs:
        idVendor: "{{ zwave_vendor }}"
        idProduct: "{{ zwave_product }}"
      symlink: "{{ zwave_usbstick_symlink }}"
  directories:
    - path: "{{ zwave_dir }}"
  files:
    - src: roles/zwave/templates/settings.json.j2
      dest: "{{ zwave_dir }}/settings.json"
  docker:
    service:
      name: zwavejs2mqtt
      config_dir: "{{ zwave_dir }}"
