- name: Load Home Automation Configuration
  set_fact:
    __home_automation_wemo_hosts: "{{ home_automation_wemo_hosts }}"
    __home_automation_reverse_proxy_ip: "{{ home_automation_reverse_proxy_ip }}"