fail2ban_jail_files: "{%- set temp_jail_files = [] -%}
                      {%- for jail in __fail2ban_jails | default([]) -%}
                      {%- set _ = temp_jail_files.append({
                          'src': 'roles/fail2ban/templates/jail.conf.j2',
                          'dest': fail2ban_dir + '/jail.d/' + jail.jail_name + '.conf',
                          'vars': jail
                      }) -%}
                      {%- endfor -%}
                      {{- temp_jail_files -}}"

fail2ban_filter_files: "{%- set temp_filter_files = [] -%}
                        {%- for filter in __fail2ban_filters | default([]) -%}
                        {%- set _ = temp_filter_files.append({
                            'src': filter.src,
                            'dest': fail2ban_dir + '/filter.d/' + filter.dest
                        }) -%}
                        {%- endfor -%}
                        {{- temp_filter_files -}}"

fail2ban_files:
  - src: "roles/fail2ban/templates/jail.local.j2"
    dest: "{{ fail2ban_dir }}/jail.local"

fail2ban_role:
  directories:
    - path: "{{ fail2ban_dir }}/jail.d"
      volume:
        name: "{{ fail2ban_jails_volume }}"
    - path: "{{ fail2ban_dir }}/filter.d"
  files: "{{ fail2ban_files + fail2ban_jail_files + fail2ban_filter_files }}"
