fail2ban_role:
  directories:
    - path: "{{ fail2ban_dir }}/jail.d"
      volume:
        name: "{{ fail2ban_jails_volume }}"
    - path: "{{ fail2ban_dir }}/filter.d"
  files:
    - src: "roles/fail2ban/templates/jail.local.j2"
      dest: "{{ fail2ban_dir }}/jail.local"
  files_changed_by_tasks: "{{ fail2ban_installed_jails.results | default([]) + fail2ban_installed_filters.results | default([]) }}"
