- name: Install prerequsites
  local_action:
    module: pip 
    name: netaddr

- name: Update dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: "{{ dhcp_dir }}/dhcpd.conf"
  register: dhcp_conf
