fish_config_root: "{{ ansible_env.HOME }}/.config/fish"

shell_role:
  packages:
    - fish
  files:
    - src: roles/shell/files/config.fish
      dest: "{{ fish_config_root }}/config.fish"
      mode: "0664"
    - src: roles/shell/files/fish_prompt.fish
      dest: "{{ fish_config_root }}/functions/fish_prompt.fish"
      mode: "0664"
    - src: roles/shell/files/fish_title.fish
      dest: "{{ fish_config_root }}/functions/fish_title.fish"
      mode: "0664"
