fish_config_root: /home/{{ ansible_env.SUDO_USER }}/.config/fish

shell_role:
  packages:
    - fish
  files:
    - src: roles/shell/files/config.fish
      dest: "{{ fish_config_root }}/config.fish"
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
      mode: "0664"
    - src: roles/shell/files/fish_prompt.fish
      dest: "{{ fish_config_root }}/functions/fish_prompt.fish"
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
      mode: "0664"
    - src: roles/shell/files/fish_title.fish
      dest: "{{ fish_config_root }}/functions/fish_title.fish"
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
      mode: "0664"
