shell_directories: "{%- set temp_shell_directories = [] -%}
                    {%- for user in (__shell_users | default([])) -%}
                    {%- set home = __shell_user_details | selectattr('name', 'equalto', user) | map(attribute='home') | first -%}
                    {%- set fish_config_root = home + '/.config/fish' -%}
                    {%- set group = __shell_user_details | selectattr('name', 'equalto', user) | map(attribute='group') | first -%}
                    {%- set _ = temp_shell_directories.append({
                        'path': fish_config_root + '/functions',
                        'owner': user,
                        'group': group
                    })-%}            
                    {%- endfor -%}
                    {{- temp_shell_directories }}"

shell_files: "{%- set temp_shell_files = [] -%}
              {%- for user in (__shell_users | default([])) -%}
              {%- set home = __shell_user_details | selectattr('name', 'equalto', user) | map(attribute='home') | first -%}
              {%- set fish_config_root = home + '/.config/fish' -%}
              {%- set group = __shell_user_details | selectattr('name', 'equalto', user) | map(attribute='group') | first -%}
              {%- set _ = temp_shell_files.append({
                  'src': 'roles/shell/files/config.fish',
                  'dest': fish_config_root + '/config.fish',
                  'owner': user,
                  'group': group
              })-%}
              {%- set _ = temp_shell_files.append({
                  'src': 'roles/shell/files/fish_prompt.fish',
                  'dest': fish_config_root + '/functions/fish_prompt.fish',
                  'owner': user,
                  'group': group
              })-%}
              {%- set _ = temp_shell_files.append({
                  'src': 'roles/shell/files/fish_title.fish',
                  'dest': fish_config_root + '/functions/fish_title.fish',
                  'owner': user,
                  'group': group
              })-%}              
              {%- endfor -%}
              {{- temp_shell_files }}"

fish_config_root: "{{ ansible_env.HOME }}/.config/fish"

shell_role:
  packages:
    - fish
  directories: "{{ shell_directories }}"
  files: "{{ shell_files }}"
