dhcp_relay_role:
  docker:
    service:
      name: "{{ dhcp_relay_service_name }}"
      image: pumbaasdad/dhcp-helper
      networks:
        host: true
      capabilities:
        - NET_ADMIN
      command: -s {{ dhcp_relay_dhcp_server_ip }}
  files:
    - src: roles/dhcp-relay/templates/Dockerfile
      dest: "{{ dockerfile_dir }}/{{ dhcp_relay_service_name }}.Dockerfile"

dhcp_relay_dhcp_server_ip: "{{dhcp_role.provides.dhcp_server_ip }}"