internal_zone: "{{ network | json_query('zones[?hosts[*].internal] | [0]') }}"
internal_host: "{{ internal_zone | json_query('hosts[?internal] | [0]') }}"
internal_ip: "{{ internal_zone.ipv4_subnet | ansible.utils.ipaddr(internal_host.ipv4_offset) | ansible.utils.ipaddr('address') }}"

certificates_role:
  directories:
    - path: "{{ letsencrypt_dir }}"
      volume:
        name: "{{ letsencrypt_certificate_volume }}"
    - path: "{{ letsencrypt_dir }}/etc"
      volume:
        name: "{{ letsencrypt_etc_volume }}"
        backup: true
  files:
    - src: roles/certificates/templates/Dockerfile
      dest: "{{ dockerfile_dir }}/{{ letsencrypt_service_name }}.Dockerfile"
    - src: roles/certificates/templates/cloudflare.ini.j2
      dest: "{{ letsencrypt_dir }}/dns-conf/cloudflare.ini"
      mode: '0600'
  docker:
    services:
      - name: "{{ letsencrypt_service_name }}"
        config_dir: "{{ fail2ban_dir }}"
        volumes:
          - "{{ letsencrypt_certificate_volume }}:/config"
          - external-proxy-log:/config/log/reverse-proxy
          - "{{ hass_dir }}/home-assistant.log:/config/log/hass/home-assistant.log"
          - fail2ban-jails:/etc/fail2ban/jail.d
        environment:
          - EMAIL={{ letsencrypt_email }}
          - URL={{ network.domain }}.{{ network.suffix }}
          - SUBDOMAINS={{ __certificates_subdomains | default([]) | join(',') }}
          - VALIDATION=dns
          - DNSPLUGIN=cloudflare
          - PROPAGATION=30
        capabilities:
          - NET_ADMIN
        backup: true
  provides:
    certificate_volume: "{{ letsencrypt_certificate_volume }}"
