dhcp_role:
  directories:
    - path: "{{ dhcp_dir }}"
  local_pip_modules:
    - netaddr
  files:
    - src: roles/dhcp/templates/dhcpd.conf.j2
      dest: "{{ dhcp_dir }}/dhcpd.conf"
  docker:
    service:
      name: dhcp
      config_dir: "{{ dhcp_dir }}"
