dhcp_role:
  directories:
    - path: "{{ dhcp_dir }}"
      volume: dhcp
  files:
    - src: roles/dhcp/templates/dhcpd.conf.j2
      dest: "{{ dhcp_dir }}/dhcpd.conf"
  docker:
    service:
      name: dhcp
      config_dir: "{{ dhcp_dir }}"
    networks:
      - name: dhcp0
        subnet: "{{ dhcp_docker_subnet }}"

local_dhcp_role:
  pip_modules:
    - netaddr
