home_automation_internal_zone: "{{ network | json_query('zones[?hosts[*].internal] | [0]') }}"
home_automation_internal_host: "{{ internal_zone | json_query('hosts[?internal] | [0]') }}"
home_automation_internal_ip: "{{ internal_zone.ipv4_subnet | ansible.utils.ipaddr(internal_host.ipv4_offset) | ansible.utils.ipaddr('address') }}"

home_automation_extra_networks: "{%- set temp_home_automation_extra_networks = { home_automation_network: {} } -%}
                                 {{- temp_home_automation_extra_networks -}}"

home_automation_role:
  directories:
    - path: "{{ hass_dir }}"
      volume:
        name: "{{ hass_config_volume }}"
        backup: true
    - path: "{{ hass_db_dir }}"
      volume:
        name: "{{ hass_db_volume }}"
  files:
    - src: roles/home-automation/files/home-assistant.log
      dest: "{{ hass_dir }}/home-assistant.log"
      force: no
    - src: roles/home-automation/templates/wemo.yaml.j2
      dest: "{{ hass_dir }}/wemo.yaml"
  intrusion_detection:
    jails:
      - jail_name: ha
        file: hass/home-assistant.log
    filters:
      - src: roles/home-automation/templates/filter.local.j2
        dest: ha.local
  reverse_proxy:
    public_site_configs:
      - src: roles/home-automation/templates/private-reverse-proxy.j2
        name: hass-private
      - src: roles/home-automation/templates/public-reverse-proxy.j2
        name: hass-public
  docker:
    service:
      name: "{{ home_automation_service_name }}"
      container_name: "{{ home_automation_container_name }}"
      image: lscr.io/linuxserver/homeassistant:latest
      volumes:
        - "{{ hass_config_volume }}:/config"
        - "{{ hass_db_volume }}:/db"
      ports:
        - "{{ home_automation_wemo_server_port }}:{{ home_automation_wemo_server_port }}"
      environment:
        - PYWEMO_HTTP_SERVER_PORT={{ home_automation_wemo_server_port }}
        - PYWEMO_CALLBACK_ADDRESS={{ home_automation_internal_ip }}:{{ home_automation_wemo_server_port }}
      networks:
        default: false
        internal: true
        extra: "{{ home_automation_extra_networks }}"
      config_dir: "{{ hass_dir }}"
      backup: true
    networks:
      - name: "{{ home_automation_network }}"
  files_changed_by_tasks: "{{ [hass_config | default(None)] | select() }}"
