octet_regex: "[0-9a-fA-F]{2}"
mac_regex: "([0-9a-fA-F])[0-9a-fA-F]:({{ octet_regex }}):({{ octet_regex }}):({{ octet_regex }}):({{ octet_regex }}):({{ octet_regex }})"
mac_to_ipv6_interface_bit_flipper: ["2", "3", "0", "1", "6", "7", "4", "5", "a", "b", "8", "9", "e","f", "c", "d"]

dns_zone_query: "zones[?name=='{{dns_zone}}'] | [0]"
dns_zone_result: "{{ network | json_query(dns_zone_query) }}"
dns_host_query: "hosts[?name=='{{dns_server}}'] | [0]"
dns_host_result: "{{ dns_zone_result | json_query(dns_host_query) }}"
dns_host_ip: "{{ dns_zone_result.ipv4_subnet | ipaddr(dns_host_result.ipv4_offset) | ipaddr('address') }}"
dns_root_domain: "{{ network.domain }}.{{ network.suffix }}"

dns_user: "100"
dns_group: "101"

reverse_ipv6_zone: "{{ ('fe80::' | ipaddr('revdns'))[32:-10] }}"

dns_zone_files: "{%- set temp_zone_files = [] -%}
                 {%- for zone in network.zones -%}
                 {%- set _ = temp_zone_files.append({
                     'src': 'roles/dns/templates/db.zone.j2',
                     'dest': dns_config_dir + '/db.' + zone.name + '.' + dns_root_domain,
                     'zone_name': zone.name,
                     'owner': dns_user,
                     'group': dns_group,
                     'mode': '0644',
                     'notify': 'Update DNS zone serial numbers',
                     'label': zone.name
                 })-%}
                 {%- set zone_octets = ((zone.ipv4_subnet | ipaddr('prefix')) / 8) | round(0, 'ceil') | int -%}
                 {%- set zone_name = (zone.ipv4_subnet | ipaddr('network') | ipaddr('revdns') | split('.'))[(4 - zone_octets):] | select() | join('.') -%}
                 {%- set _ = temp_zone_files.append({
                     'src': 'roles/dns/templates/db.reverse_ipv4_zone.j2',
                     'dest': dns_config_dir + '/db.' + zone_name[:-13],
                     'zone_name': zone.name,
                     'reverse_zone_name': zone_name,
                     'owner': dns_user,
                     'group': dns_group,
                     'mode': '0644',
                     'notify': 'Update DNS zone serial numbers',
                     'label': zone_name
                 })-%}
                 {%- set zone_name = (zone.ipv4_subnet | ipaddr('network') | ipmath(256) | ipaddr('revdns') | split('.'))[(4 - zone_octets):] | select() | join('.') -%}
                 {%- set _ = temp_zone_files.append({
                     'src': 'roles/dns/templates/db.reverse_ipv4_zone.j2',
                     'dest': dns_config_dir + '/db.' + zone_name[:-13],
                     'zone_name': zone.name,
                     'reverse_zone_name': zone_name,
                     'owner': dns_user,
                     'group': dns_group,
                     'mode': '0644',
                     'notify': 'Update DNS zone serial numbers',
                     'label': zone_name
                 })-%}                                                  
                 {%- endfor -%}
                 {{- temp_zone_files -}}"

dns_files:
  - src: roles/dns/files/db.0
    dest: "{{ dns_config_dir }}"
    force: no
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    mode: "0644"
  - src: roles/dns/files/db.127
    dest: "{{ dns_config_dir }}"
    force: no
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    mode: "0644"
  - src: roles/dns/files/db.255
    dest: "{{ dns_config_dir }}"
    force: no
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    mode: "0644"
  - src: roles/dns/files/db.empty
    dest: "{{ dns_config_dir }}"
    force: no
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    mode: "0644"
  - src: roles/dns/files/db.local
    dest: "{{ dns_config_dir }}"
    force: no
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    mode: "0644"
  - src: roles/dns/files/db.root
    dest: "{{ dns_config_dir }}"
    force: no
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    mode: "0644"
  - src: roles/dns/files/named.conf
    dest: "{{ dns_config_dir }}"
    force: no
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    mode: "0644"
  - src: roles/dns/files/named.conf.default-zones
    dest: "{{ dns_config_dir }}"
    force: no
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    mode: "0644"
  - src: roles/dns/templates/named.conf.local.j2
    dest: "{{ dns_config_dir }}/named.conf.local"
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    mode: "0644"
  - src: roles/dns/templates/named.conf.options.j2
    dest: "{{ dns_config_dir }}/named.conf.options"
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    mode: "0644"
  - src: roles/dns/templates/db.root_zone.j2
    dest: "{{ dns_config_dir }}/db.{{ dns_root_domain }}"
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    zone_name: "{{ dns_root_domain }}"
    mode: "0644"
    notify: Update DNS zone serial numbers
  - src: roles/dns/templates/db.reverse_ipv6_link_local_zone.j2
    dest: "{{ dns_config_dir }}/db.{{ reverse_ipv6_zone }}"
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    zone_name: "{{ reverse_ipv6_zone }}"
    mode: "0644"
    notify: Update DNS zone serial numbers
  - src: roles/dns/templates/resolv.conf.j2
    dest: /etc/resolv.conf

dns_role:
  directories:
    - path: "{{ dns_config_dir }}"
    - path: "{{ dns_cache_dir }}"
      owner: "{{ dns_user }}"
      group: "{{ dns_group }}"
  local_pip_modules:
    - dnspython
    - netaddr
    - jinja2
    - jmespath
  disabled_services:
    - systemd-resolved
  files: "{{ dns_files + dns_zone_files }}"

  docker:
    service:
      name: dns
      config_dir: "{{ dns_dir }}"
