dns_role:
  packages:
    - bind9
  service: bind9

octet_regex: "[0-9a-fA-F]{2}"
mac_regex: "([0-9a-fA-F])[0-9a-fA-F]:({{ octet_regex }}):({{ octet_regex }}):({{ octet_regex }}):({{ octet_regex }}):({{ octet_regex }})"
mac_to_ipv6_interface_bit_flipper: ["2", "3", "0", "1", "6", "7", "4", "5", "a", "b", "8", "9", "e","f", "c", "d"]