docker_host_packages:
  apt:
    name: docker
    key: https://download.docker.com/linux/ubuntu/gpg
    repository: https://download.docker.com/linux/ubuntu
    distribution: noble
    arch: amd64
    components:
      - stable
    packages:
      docker-buildx-plugin: 0.33.0-1~ubuntu.24.04~noble
      docker-ce: 5:29.4.0-1~ubuntu.24.04~noble
      docker-ce-cli: 5:29.4.0-1~ubuntu.24.04~noble
      docker-compose-plugin: 5.1.3-1~ubuntu.24.04~noble
      containerd.io: 2.2.3-1~ubuntu.24.04~noble
