- become: true
  block:
    - name: Install packages
      apt:
        name:
          - libpam-u2f
          - pamu2fcfg
        update_cache: true
        cache_valid_time: "{{ yubikey_apt_cache_valid_time }}"

- name: Create Yubico config directory
  file:
    path: /root/.config/Yubico
    state: directory
    mode: 0755

- name: Require Yubikey for physical login
  copy:
    src: login
    dest: /etc/pam.d/login