media_rip_dir: "{{ docker_compose_dir }}/media-rip"
media_rip_config_dir: "{{ media_rip_dir }}/config"
media_rip_output_dir: "{{ media_rip_dir }}/output"
media_rip_keep_app_running: 1

optical_vendor: "{{ secrets['optical_vendor'] }}"
