volumerize_standard_volumes:
  - "{{ volumerize_cache_volume }}:/volumerize-cache"
  - "{{ volumerize_credentials_volume }}:/credentials"
  - /var/run/docker.sock:/var/run/docker.sock

volumerize_lazy_containers_to_stop: "{%- set temp_volumerize_lazy_containers_to_stop = [] -%}
                                     {%- for service in backup_services -%}
                                     {%- set _ = temp_volumerize_lazy_containers_to_stop.append(service.container_name | default(service.name)) -%}
                                     {%- endfor -%} 
                                     {{- temp_volumerize_lazy_containers_to_stop -}}"

backup_role:
  directories:
    - path: "{{ volumerize_dir }}/cache"
      volume:
        name: "{{ volumerize_cache_volume }}"
    - path: "{{ volumerize_dir }}/credentials"
      volume:
        name: "{{ volumerize_credentials_volume }}"
  files:
    - src: roles/backup/templates/Dockerfile
      dest: "{{ dockerfile_dir }}/{{ volumerize_service_name }}.Dockerfile"
    - src: roles/backup/templates/google_service_account.json.j2
      dest: "{{ volumerize_dir }}/credentials/google_service_account.json"
  docker:
    service:
      name: "{{ volumerize_service_name }}"
      volumes: "{{ volumerize_standard_volumes + (__volumerize_custom_volumes | default([])) }}"
      environment:
        - VOLUMERIZE_SOURCE=/source
        # - VOLUMERIZE_TARGET=gdocs://{{ volumerize_email }}/{{ volumerize_google_drive_dir }}
        - VOLUMERIZE_TARGET=gdrive://{{ volumerize_google_service_account_email }}?myDriveFolderID={{ volumerize_google_drive_folder_id }}
        - VOLUMERIZE_EXCLUDE_1=**/*.log*
        - PASSPHRASE={{ volumerize_passphrase }}
        - VOLUMERIZE_JOBBER_TIME={{ volumerize_schedule }}
        - VOLUMERIZE_CONTAINERS={{ __volumerize_containers_to_stop | default('') }}
        - VOLUMERIZE_FULL_IF_OLDER_THAN={{ volumerize_full_if_older_than }}
        - REMOVE_ALL_BUT_N_FULL={{ volumerize_remove_all_but_n_full }}
        - REMOVE_ALL_INC_BUT_N_FULL={{ volumerize_all_inc_but_n_full }}
        - GOOGLE_SERVICE_JSON_FILE=/credentials/google_service_account.json
