- name: Create cups config dir
  file:
    path: "{{ cups_dir }}"
    state: directory

- name: Create the udev rule for the usb printer
  template:
    src: printer.rules.j2
    dest: /etc/udev/rules.d/printer.rules
  notify: Reload udev rules
