- name: Mount media library
  mount:
    src: "{{ media_server_src_dir }}"
    path: "{{ media_server_dest_dir }}"
    fstype: nfs
    opts: noauto,nofail,x-systemd.automount,x-systemd.device-timeout=10,x-systemd.requires=isc-dhcp-server.service,soft,intr,rsize=8192
    state: mounted

- name: Install prerequsites
  apt:
    name:
      - curl
      - git
      - wget
    state: latest
    update_cache: true

- name: Find most recent version of plex
  shell: curl https://plex.tv/api/downloads/5.json | grep -o '"label"[^}]*' | grep 'Ubuntu' | grep '64-bit' | grep -oP '"url":"\K[^"]*' | grep -oP 'plexmediaserver_\K[^_]*'
  args:
    warn: false
  register: latest_plex_version
  changed_when: false

- name: Check if plex is installed
  shell: dpkg-query -s plexmediaserver
  changed_when: false
  failed_when: false
  register: plex_installed

- name: Update plexupdate repository
  git:
    repo: https://github.com/mrworf/plexupdate.git
    dest: "{{ plexupdate_dir }}"

- name: Check if plex is running
  shell: |
    source {{ plexupdate_dir }}
    ! running 127.0.0.1 32400
    exit $?
  changed_when: false
  failed_when: false
  register: plex_running
  when: plex_installed.rc == 0

- name: Install plex
  apt:
    deb: https://downloads.plex.tv/plex-media-server-new/{{ latest_plex_version.stdout }}/debian/plexmediaserver_{{ latest_plex_version.stdout }}_amd64.deb
  when: plex_installed.rc == 1 or plex_running.rc == 0
