iptables_role:
  packages:
    - iptables-persistent
    - netfilter-persistent
  root_directories:
    - path: /etc/systemd/system/netfilter-persistent.service.d
  root_files:
    - src: roles/iptables/files/override.conf
      dest: /etc/systemd/system/netfilter-persistent.service.d/override.conf
      notify: Reload systemd for netfilter-persistent
  service: netfilter-persistent
