- name: Create media-rip directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ media_rip_config_dir }}"
    - "{{ media_rip_output_dir }}"

- name: Find optical drives
  stat:
    path: "{{ item }}"
  with_items:
    - /dev/{{ media_rip_block_device_symlink }}
    - /dev/{{ media_rip_scsi_generic_device_symlink }}
  register: optical_drives
