- name: Create the udev rule for the optical drive
  template:
    src: scsi.rules.j2
    dest: /etc/udev/rules.d/scsi.rules
  register: scsi_udev_rules

- name: Create media-rip directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ media_rip_config_dir }}"
    - "{{ media_rip_output_dir }}"