docker_address_pool_subnet: "{{ lookup('lastpass', lastpass_secrets_path + '/docker_address_pool_subnet') }}"
docker_private0_subnet: "{{ lookup('lastpass', lastpass_secrets_path + '/docker_private0_subnet') }}"

public_port: "{{ lookup('lastpass', lastpass_secrets_path + '/public_port') }}"
nas_address: "{{ lookup('lastpass', lastpass_secrets_path + '/nas_address') }}"

secrets_dir: "{{ lookup('lastpass', lastpass_secrets_path + '/secrets_dir') }}"
