name: Depend APT Bot

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean
  schedule:
    - cron: '0 6 * * 6'

jobs:
  depend-apt-bot:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    strategy:
      matrix:
        include:
          - file: roles/cloudflared/vars/ubuntu.yml
            key: cloudflared_packages
            name: cloudflared
          - file: roles/mongo/vars/ubuntu_8.yml
            key: mongo_packages
            name: mongo
          - file: roles/core/vars/ubuntu.yml
            key: core_fish_packages
            name: ubuntu-fish
          - file: roles/core/vars/debian.yml
            key: core_fish_packages
            name: debian-fish
          - file: roles/java/vars/ubuntu_adoptium.yml
            key: java_packages
            name: adoptium-java
          - file: roles/unifi/vars/ubuntu.yml
            key: unifi_packages
            name: unifi
          - file: roles/docker_host/vars/ubuntu.yml
            key: docker_host_packages
            name: docker
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: .github/actions/depend-apt-bot/yarn.lock

      - name: Install dependencies
        run: yarn install
        working-directory: ./.github/actions/depend-apt-bot

      - name: Run depend-apt-bot for ${{ matrix.name }}
        uses: ./.github/actions/depend-apt-bot
        with:
          file: ${{ matrix.file }}
          key: ${{ matrix.key }}
          package-manager: apt
        id: update-packages

      - name: Create Pull Request for ${{ matrix.name }}
        if: steps.update-packages.outputs.updated == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: depend-apt-bot/${{ matrix.name }}
          commit-message: '[depend-apt-bot] Update ${{ matrix.name }} packages'
          title: 'Update ${{ matrix.name }} packages'
          body: |
            Updated packages in `${{ matrix.file }}`:
            ${{ steps.update-packages.outputs.updated-packages }}
            
            🤖 Auto-generated by depend-apt-bot
          delete-branch: true
          labels: dependencies,apt
