ssh_authorized_key: "{{ lookup('lastpass', lastpass_secrets_path + '/ssh_authorized_key') }}"

yubikey_token_id: "{{ lookup('lastpass', lastpass_secrets_path + '/yubikey_token_id') }}"
yubico_api_client_id: "{{ lookup('lastpass', lastpass_secrets_path + '/yubico_api_client_id') }}"
yubico_api_secret_key: "{{ lookup('lastpass', lastpass_secrets_path + '/yubico_api_secret_key') }}"
